/**
 * Phase 5 + 6 — Render and Send.
 *
 * Renders the digest sections into HTML via @workspace/email's React
 * Email templates, then sends via the @workspace/email Resend wrapper.
 *
 * The CRON_SECRET check lives at the route handler — `runDailyDigest`
 * is the inner workflow (testable without an HTTP request).
 */
import { render } from "react-email";
import { createEmailClient } from "@workspace/email";
import { EmailShell, DigestBlock, type RagStatus } from "@workspace/email/templates";
import { env } from "../env.ts";

import type { DailyDigest } from "./digest-schema.ts";

const email = createEmailClient({
  apiKey: env.RESEND_API_KEY,
  from: { name: env.RESEND_FROM_NAME, address: env.RESEND_FROM_ADDRESS },
  ...(env.RESEND_REPLY_TO !== undefined ? { replyTo: env.RESEND_REPLY_TO } : {}),
  unsubscribeBaseUrl: env.UNSUBSCRIBE_BASE_URL,
  unsubscribeMailto: env.UNSUBSCRIBE_MAILTO,
});

const STATUS_BY_SECTION: Record<string, RagStatus> = {
  tldr: "yellow",
  shipped: "green",
  risks: "red",
  watchlist: "yellow",
};

export async function renderAndSendDigest(opts: {
  digest: DailyDigest;
  digestId: string;
  dryRun?: boolean;
}): Promise<{ messageId: string; dryRunPath?: string }> {
  const { digest, digestId, dryRun = false } = opts;

  const subject = `Daily digest — ${digest.date} [${digestId}]`;

  const header = `Org: ${env.GITHUB_ORG} · Data as of ${digest.date} 22:00 UTC · Digest ID: ${digestId}`;
  const footer = `Generated by the Technical Analyst. List-Unsubscribe: <${env.UNSUBSCRIBE_BASE_URL}/unsubscribe/${digestId}>, <mailto:${env.UNSUBSCRIBE_MAILTO}>.`;

  const html = await render(
    <EmailShell subject={subject} header={header} footer={footer}>
      {digest.sections.map((section) => {
        const status = STATUS_BY_SECTION[section.kind];
        return (
          <DigestBlock
            key={section.kind}
            kind={section.kind as "tldr" | "shipped" | "risks" | "watchlist"}
            text={section.text}
            {...(status !== undefined ? { status } : {})}
          />
        );
      })}
    </EmailShell>,
  );

  // Plain-text fallback: emit one line per section.
  const text = digest.sections.map((s) => `${s.kind.toUpperCase()}: ${s.text}`).join("\n\n");

  if (dryRun) {
    const path = `tmp/preview-${digest.date}-daily-${digestId}.html`;
    await import("node:fs/promises").then((fs) => fs.writeFile(path, html, "utf8"));
    return { messageId: "dryrun", dryRunPath: path };
  }

  const result = await email.send({
    to: env.DIGEST_RECIPIENT,
    subject,
    html,
    text,
    digestId,
    tags: [
      { name: "agent", value: "technical-analyst" },
      { name: "kind", value: "daily" },
      { name: "digest_id", value: digestId },
    ],
  });

  return { messageId: result.id };
}
